export enum ApiDienstverwendung {
  ADMINISTRATOR_IN = "Administrator/in",
  AGILE_COACH = "Agile Coach",
  ASSISTENT_IN = "Assistent/in",
  AUSBILDUNGSBEAUFTRAGTE_R = "Ausbildungsbeauftragte/in",
  DATENBANKADMINISTRATOR_IN = "Datenbankadministrator/in)",
  DEMAND_MANAGER_IN = "Demand Manager/in",
  DEVELOPER = "Developer",
  ENTERPRISE_ARCHITEKT_IN = "Enterprise Architekt/in",
  HAUSTECHNIKER_IN = "Haustechniker/in",
  INFRASTRUKTUR_ARCHITEKT_IN = "Infrastruktur Architekt/in",
  IT_ANALYST_IN = "IT-Analyst/in",
  IT_CONSULTANT = "IT-Consultant",
  IT_MANAGER_IN = "IT-Manager/in",
  IT_SUPPORT = "IT-Support",
  NETZWERKADMINISTRATOR_IN = "Netzwerkadministrator/in",
  PORTIERFUNKTION = "Platform Engineer",
  PRODUCT_OWNER = "Product Owner",
  PROJEKTLEITER_IN = "Projektleiter/in",
  PROJEKTMANAGER_IN = "Projektmanager/in",
  SERVICEMANAGER_IN = "Servicemanager/in",
  SOFTWARE_ARCHITEKT_IN = "Software Architekt/in",
  SOFTWARE_DEVELOPER_IN = "Software Developer/in",
  SYSTEMADMINISTRATOR_IN = "Systemadministrator/in",
  TEST_ARCHITEKT_IN = "Test Architekt/in",
  TEST_ENGINEER = "Test Engineer",
  TEST_MANAGER_IN = "Test Manager/in",
  ZIVILDIENSTLEISTENDER = "Zivildienstleistender",
  PRAKTIKANT_IN = "Praktikant(in)",
  REFERENT_IN = "Referent(in)",
  LEITER_IN = "Leiter(in)",
  SEKRETAER_IN = "Sekret\u00e4r(in)",
  BENUTZERBETREUER_IN = "Benutzerbetreuer(in)",
  ARBEITSVORBEREITUNG_OPERATOR = "Arbeitsvorbereitung-Operator",
  ARBEITSBETREUER_IN = "Arbeitsbetreuer(in)",
  OPERATOR = "Operator",
  ARBEITSVORBEREITUNG_PROGRAMMIERER_IN = "Arbeitsvorbereitung_Programmierer(in)",
  PROGRAMMIERER_IN = "Programmierer(in)",
  CHEFOPERATOR = "Chefoperator",
  REFERATSLEITER_IN = "Referatsleiter(in)",
  STELLVERTRETENDE_R_LEITER_IN = "stellvertretende(r) Leiter(in)",
  STELLVERTRETENDE_R_REFERATSLEITER_IN = "stellvertretende(r) Referatsleiter(in)",
  NETZWERKADMINISTRATOR_ASSISTENT_IN = "Netzwerkadministrator-Assistent(in)",
  CHEFORGANISATOR_IN = "Cheforganisator(in)",
  ORGANISATOR_IN = "Organisator(in)",
  ORGANISATIONSASSISTENT_IN = "Organisationsassistent(in)",
  ANALYTIKERASSISTENT_IN = "Analytikerassistent(in)",
  CHEFANALYTIKER_IN = "Chefanalytiker(in)",
  ARBEITER_IN = "Arbeiter(in)",
  AMTSWART_IN = "Amtswart(in)",
  TEAMASSISTENT_IN = "Teamassistent(in)",
  KOORDINATOR_IN = "Koordinator(in)",
  BETREUER_IN = "Betreuer(in)",
  OPERATOR_IN_AUSBILDUNG = "Operator in Ausbildung",
  ANALYTIKER_IN = "Analytiker(in)",
  RICHTFUNKTION_F_D_BEDIENSTETENGRUPPE_2 = "Richtfunktion f.d. Bedienstetengruppe 2",
  APPLIKATIONSADMINISTRATOR_IN = "Applikationsadministrator(in)",
  APPLIKATIONSLEITER_IN = "Applikationsleiter(in)",
  CHEF_DATENBANKORGANISATOR_IN = "Chef-Datenbankorganisator(in)",
  CHEF_NETZWERKORGANISATOR_IN = "Chef-Netzwerkorganisator(in)",
  SYSTEMORGANISATOR_IN = "Systemorganisator(in)",
  LEITER_IN_DER_SOFTWARE = "Leiter(in) der Software",
  LEITER_IN_IT_DIENST = "Leiter(in) IT-Dienst",
  CHEFPROGRAMMIERER_IN = "Chefprogrammierer(in)",
  LEITER_IN_VERARBEITUNG = "Leiter(in) Verarbeitung",
  LEITER_IN_ARBEITSVORBEREITUNG = "Leiter(in) Arbeitsvorbereitung",
  LEITER_IN_BENUTZERBETREUUNG = "Leiter(in) Benutzerbetreuung",
  LEITER_IN_OPERATION = "Leiter(in) Operation",
  SENIORPROGRAMMIERER_IN = "Seniorprogrammierer(in)",
  SYSTEMPROGRAMMIERER_IN = "Systemprogrammierer(in)",
  AUSBILDUNGSBEAUFTRAGTER_ASSISTENT_IN = "Ausbildungsbeauftragter-Assistent(in)",
  ARBEITSVORBEREITUNG_SYSTEMOPERATOR_IN = "Arbeitsvorbereitung-Systemoperator(in)",
  BENUTZERBETREUER_ASSISTENT_IN = "Benutzerbetreuer-Assistent(in)",
  LEITER_IN_DATENERFASSUNG = "Leiter(in) Datenerfassung",
  PROGRAMMIERASSISTENT_IN = "Programmierassistent(in)",
  SYSTEMOPERATOR_IN = "Systemoperator(in)",
  GRUPPENLEITER_IN_DATENERFASSUNG = "Gruppenleiter(in) Datenerfassung",
  ORGANISATOR_IN_ANALYTIKER_IN = "Organisator(in)/Analytiker(in)",
  ORGANISATIONSASSISTENT_IN_ANALYTIKERASSISTENT_IN = "Organisationsassistent(in)/Analytikerassistent(in)",
  SEKRETARIATSLEITER_IN = "Sekretariatsleiter(in)",
  TESTER_IN = "Tester(in)",
  ARCHITEKT_IN = "Architekt(in)",
  REQUIREMENTS_ENGINEER = "Requirements Engineer",
}

export function getApiDienstverwendungDisplayValues(): { key: ApiDienstverwendung, value: string }[] {
  return [
    { key: ApiDienstverwendung.ADMINISTRATOR_IN, value: "Administrator/in" },
    { key: ApiDienstverwendung.AGILE_COACH, value: "Agile Coach" },
    { key: ApiDienstverwendung.ASSISTENT_IN, value: "Assistent/in" },
    { key: ApiDienstverwendung.AUSBILDUNGSBEAUFTRAGTE_R, value: "Ausbildungsbeauftragte/in" },
    { key: ApiDienstverwendung.DATENBANKADMINISTRATOR_IN, value: "Datenbankadministrator/in)" },
    { key: ApiDienstverwendung.DEMAND_MANAGER_IN, value: "Demand Manager/in" },
    { key: ApiDienstverwendung.DEVELOPER, value: "Developer" },
    { key: ApiDienstverwendung.ENTERPRISE_ARCHITEKT_IN, value: "Enterprise Architekt/in" },
    { key: ApiDienstverwendung.HAUSTECHNIKER_IN, value: "Haustechniker/in" },
    { key: ApiDienstverwendung.INFRASTRUKTUR_ARCHITEKT_IN, value: "Infrastruktur Architekt/in" },
    { key: ApiDienstverwendung.IT_ANALYST_IN, value: "IT-Analyst/in" },
    { key: ApiDienstverwendung.IT_CONSULTANT, value: "IT-Consultant" },
    { key: ApiDienstverwendung.IT_MANAGER_IN, value: "IT-Manager/in" },
    { key: ApiDienstverwendung.IT_SUPPORT, value: "IT-Support" },
    { key: ApiDienstverwendung.NETZWERKADMINISTRATOR_IN, value: "Netzwerkadministrator/in" },
    { key: ApiDienstverwendung.PORTIERFUNKTION, value: "Platform Engineer" },
    { key: ApiDienstverwendung.PRODUCT_OWNER, value: "Product Owner" },
    { key: ApiDienstverwendung.PROJEKTLEITER_IN, value: "Projektleiter/in" },
    { key: ApiDienstverwendung.PROJEKTMANAGER_IN, value: "Projektmanager/in" },
    { key: ApiDienstverwendung.SERVICEMANAGER_IN, value: "Servicemanager/in" },
    { key: ApiDienstverwendung.SOFTWARE_ARCHITEKT_IN, value: "Software Architekt/in" },
    { key: ApiDienstverwendung.SOFTWARE_DEVELOPER_IN, value: "Software Developer/in" },
    { key: ApiDienstverwendung.SYSTEMADMINISTRATOR_IN, value: "Systemadministrator/in" },
    { key: ApiDienstverwendung.TEST_ARCHITEKT_IN, value: "Test Architekt/in" },
    { key: ApiDienstverwendung.TEST_ENGINEER, value: "Test Engineer" },
    { key: ApiDienstverwendung.TEST_MANAGER_IN, value: "Test Manager/in" },
    { key: ApiDienstverwendung.ZIVILDIENSTLEISTENDER, value: "Zivildienstleistender" },
    { key: ApiDienstverwendung.PRAKTIKANT_IN, value: "Praktikant(in)" },
    { key: ApiDienstverwendung.REFERENT_IN, value: "Referent(in)" },
    { key: ApiDienstverwendung.LEITER_IN, value: "Leiter(in)" },
    { key: ApiDienstverwendung.SEKRETAER_IN, value: "Sekret\u00e4r(in)" },
    { key: ApiDienstverwendung.BENUTZERBETREUER_IN, value: "Benutzerbetreuer(in)" },
    { key: ApiDienstverwendung.ARBEITSVORBEREITUNG_OPERATOR, value: "Arbeitsvorbereitung-Operator" },
    { key: ApiDienstverwendung.ARBEITSBETREUER_IN, value: "Arbeitsbetreuer(in)" },
    { key: ApiDienstverwendung.OPERATOR, value: "Operator" },
    { key: ApiDienstverwendung.ARBEITSVORBEREITUNG_PROGRAMMIERER_IN, value: "Arbeitsvorbereitung_Programmierer(in)" },
    { key: ApiDienstverwendung.PROGRAMMIERER_IN, value: "Programmierer(in)" },
    { key: ApiDienstverwendung.CHEFOPERATOR, value: "Chefoperator" },
    { key: ApiDienstverwendung.REFERATSLEITER_IN, value: "Referatsleiter(in)" },
    { key: ApiDienstverwendung.STELLVERTRETENDE_R_LEITER_IN, value: "stellvertretende(r) Leiter(in)" },
    { key: ApiDienstverwendung.STELLVERTRETENDE_R_REFERATSLEITER_IN, value: "stellvertretende(r) Referatsleiter(in)" },
    { key: ApiDienstverwendung.NETZWERKADMINISTRATOR_ASSISTENT_IN, value: "Netzwerkadministrator-Assistent(in)" },
    { key: ApiDienstverwendung.CHEFORGANISATOR_IN, value: "Cheforganisator(in)" },
    { key: ApiDienstverwendung.ORGANISATOR_IN, value: "Organisator(in)" },
    { key: ApiDienstverwendung.ORGANISATIONSASSISTENT_IN, value: "Organisationsassistent(in)" },
    { key: ApiDienstverwendung.ANALYTIKERASSISTENT_IN, value: "Analytikerassistent(in)" },
    { key: ApiDienstverwendung.CHEFANALYTIKER_IN, value: "Chefanalytiker(in)" },
    { key: ApiDienstverwendung.ARBEITER_IN, value: "Arbeiter(in)" },
    { key: ApiDienstverwendung.AMTSWART_IN, value: "Amtswart(in)" },
    { key: ApiDienstverwendung.TEAMASSISTENT_IN, value: "Teamassistent(in)" },
    { key: ApiDienstverwendung.KOORDINATOR_IN, value: "Koordinator(in)" },
    { key: ApiDienstverwendung.BETREUER_IN, value: "Betreuer(in)" },
    { key: ApiDienstverwendung.OPERATOR_IN_AUSBILDUNG, value: "Operator in Ausbildung" },
    { key: ApiDienstverwendung.ANALYTIKER_IN, value: "Analytiker(in)" },
    { key: ApiDienstverwendung.RICHTFUNKTION_F_D_BEDIENSTETENGRUPPE_2, value: "Richtfunktion f.d. Bedienstetengruppe 2" },
    { key: ApiDienstverwendung.APPLIKATIONSADMINISTRATOR_IN, value: "Applikationsadministrator(in)" },
    { key: ApiDienstverwendung.APPLIKATIONSLEITER_IN, value: "Applikationsleiter(in)" },
    { key: ApiDienstverwendung.CHEF_DATENBANKORGANISATOR_IN, value: "Chef-Datenbankorganisator(in)" },
    { key: ApiDienstverwendung.CHEF_NETZWERKORGANISATOR_IN, value: "Chef-Netzwerkorganisator(in)" },
    { key: ApiDienstverwendung.SYSTEMORGANISATOR_IN, value: "Systemorganisator(in)" },
    { key: ApiDienstverwendung.LEITER_IN_DER_SOFTWARE, value: "Leiter(in) der Software" },
    { key: ApiDienstverwendung.LEITER_IN_IT_DIENST, value: "Leiter(in) IT-Dienst" },
    { key: ApiDienstverwendung.CHEFPROGRAMMIERER_IN, value: "Chefprogrammierer(in)" },
    { key: ApiDienstverwendung.LEITER_IN_VERARBEITUNG, value: "Leiter(in) Verarbeitung" },
    { key: ApiDienstverwendung.LEITER_IN_ARBEITSVORBEREITUNG, value: "Leiter(in) Arbeitsvorbereitung" },
    { key: ApiDienstverwendung.LEITER_IN_BENUTZERBETREUUNG, value: "Leiter(in) Benutzerbetreuung" },
    { key: ApiDienstverwendung.LEITER_IN_OPERATION, value: "Leiter(in) Operation" },
    { key: ApiDienstverwendung.SENIORPROGRAMMIERER_IN, value: "Seniorprogrammierer(in)" },
    { key: ApiDienstverwendung.SYSTEMPROGRAMMIERER_IN, value: "Systemprogrammierer(in)" },
    { key: ApiDienstverwendung.AUSBILDUNGSBEAUFTRAGTER_ASSISTENT_IN, value: "Ausbildungsbeauftragter-Assistent(in)" },
    { key: ApiDienstverwendung.ARBEITSVORBEREITUNG_SYSTEMOPERATOR_IN, value: "Arbeitsvorbereitung-Systemoperator(in)" },
    { key: ApiDienstverwendung.BENUTZERBETREUER_ASSISTENT_IN, value: "Benutzerbetreuer-Assistent(in)" },
    { key: ApiDienstverwendung.LEITER_IN_DATENERFASSUNG, value: "Leiter(in) Datenerfassung" },
    { key: ApiDienstverwendung.PROGRAMMIERASSISTENT_IN, value: "Programmierassistent(in)" },
    { key: ApiDienstverwendung.SYSTEMOPERATOR_IN, value: "Systemoperator(in)" },
    { key: ApiDienstverwendung.GRUPPENLEITER_IN_DATENERFASSUNG, value: "Gruppenleiter(in) Datenerfassung" },
    { key: ApiDienstverwendung.ORGANISATOR_IN_ANALYTIKER_IN, value: "Organisator(in)/Analytiker(in)" },
    { key: ApiDienstverwendung.ORGANISATIONSASSISTENT_IN_ANALYTIKERASSISTENT_IN, value: "Organisationsassistent(in)/Analytikerassistent(in)" },
    { key: ApiDienstverwendung.SEKRETARIATSLEITER_IN, value: "Sekretariatsleiter(in)" },
    { key: ApiDienstverwendung.TESTER_IN, value: "Tester(in)" },
    { key: ApiDienstverwendung.ARCHITEKT_IN, value: "Architekt(in)" },
    { key: ApiDienstverwendung.REQUIREMENTS_ENGINEER, value: "Requirements Engineer" },
  ];
}
